name: flutter_scaffold
description: The Scaffolding for Flutter, developed by MingYCheung.
repository: https://gitee.com/MingYCheung/FLScaffold

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  # share from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/share]
  share: ^0.6.5+4
  # open_file from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/open_file]
  open_file: ^3.0.3
  # connectivity from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/connectivity]
  connectivity: ^2.0.2
  # html from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/html]
  html: ^0.14.0+4
  # markdown from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/markdown]
  markdown: ^3.0.0
  # url_launcher from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/url_launcher]
  url_launcher: ^5.7.10
  # fluro from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/fluro]
  fluro: ^1.7.8
  # archive from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/archive]
  archive: ^2.0.13
  # sqflite from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/sqflite]
  sqflite: ^1.3.2+1
  # path_provider from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/path_provider]
  path_provider: ^1.6.24
  # permission_handler from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/permission_handler]
  permission_handler: ^5.0.1+1
  # device_info from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/device_info]
  device_info: ^1.0.0
  # shared_preferences from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/shared_preferences]
  shared_preferences: ^0.5.12+4
  # dio from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/dio]
  dio: ^3.0.10
  # provider from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/provider]
  provider: ^4.3.2+3
  # RxDart from pub.flutter-io.cn [https://pub.flutter-io.cn/packages/rxdart]
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
